### ISSUE TITLE
What is the max client version it works for?

### ISSUE THREAD

**Issue by a7mdragab** [darkfoxdeveloper/SmartConquerLoader#1]
Hey bro,
What is the max client version it works for?
Thanks

**Comment by darkfoxdeveloper** [comment]
66XX is the last client version compatibility.

**Comment by a7mdragab** [comment]
> 66XX is the last client version compatibility.

Good.
Is it upgradable?
what is needed to run on 70XX?
Thanks

**Comment by darkfoxdeveloper** [comment]
has changed some things the client would not know to tell you that it is necessary

**Comment by a7mdragab** [comment]
> has changed some things the client would not know to tell you that it is necessary

OK, Thanks.
